### ISSUE TITLE
Unexpected uninterpreted exception errors from Merlin

### ISSUE THREAD

**Issue by yminsky** [janestreet/jbuilder#196]
I'm not 100% sure if this is a Merlin or a jbuilder bug. But when using jbuilder beta10 and the latest Merlin 3.0.0, and following the instructions here:

http://jbuilder.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program-using-core-and-jane-street-ppxs

Merlin spits back "Uninterpreted extension 'sexp'." in the file in question. I get similar errors when using ppx_let (e.g., let%bind), and invoking merlin-use from emacs to include ppx_jane or ppx_let doesn't help.

Oddly, some syntax extensions do appear to be in force.  Things like:

``` ocaml
type z = int [@@deriving sexp]
```
are not flagged as errors.

**Comment by yminsky** [comment]
Upon further experimentation, the [@@deriving sexp] declarations aren't flagged as errors, but they don't generate the correct value declarations either, so z_of_sexp and sexp_of_z are undefined as far as Merlin is concerned.

**Comment by diml** [comment]
Where are you seeing this? I'm seeing the same problem on my development machine at Jane Street, and it's not limited to ppx, plain libraries are ignored as well. The problem seems to be due to our emacs setup. I asked @trefis who said it should be fixable

**Comment by yminsky** [comment]
I saw this on my home machine with both emacs and atom, though it
disappeared when I switched to vscode.

**Comment by bmillwood** [comment]
I see this on vim too, but I had always chalked it up to "my vim setup is weird" without examining it further.

**Comment by diml** [comment]
And to be clear, is it only the ppx stuff that's broken? I.e. does merlin have access to libraries listed in the jbuild file?

**Comment by yminsky** [comment]
My version of this bug is very narrow: the libraries are all there, just the PPXs aren't.

**Comment by diml** [comment]
This seems to be due to a change in merlin 3.0.0, #201 should fix this issue

**Comment by struktured** [comment]
FWIW #201 did not fix the issue for my stack. ```[@@deriving sexp]``` is entirely ignored by merlin still.

**Comment by diml** [comment]
You need to pin ocaml-migrate-parsetree to the development version

**Comment by struktured** [comment]
works now, thanks!

**Comment by yminsky** [comment]
I'm still seeing issues with this, both with ocaml-migrate-parsetree pinned to the development version, and without. Also, anyone know if the relevant ocaml-migrate-parsetree has been released?

**Comment by yminsky** [comment]
Ah, my mistake. I needed to pin jbuilder as well, at which point the problem was indeed resolved.

I wonder if it's time for another jbuilder beta...
