### ISSUE TITLE
Missing quotes in flags in .merlin

### ISSUE THREAD

**Issue by mseri** [janestreet/jbuilder#198]
In https://github.com/xapi-project/nbd/pull/61 we are using an horrible hack to be able to start using jbuilder in packages that we cannot currently port to new libraries. Everything seems to work, with the only exception of the generated merlin file. It looks like a bug in jbuilder. Quoting from the comments in the PR:
> it omits the quotes in the `.merlin` file:
```
FLG -open Nbd -ppx /home/gabori/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/gabori/.opam/4.02.3/lib/ppx_core/./ppx_core.cma /home/gabori/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv_expander.cma /home/gabori/.opam/4.02.3/lib/ppx_optcomp/./ppx_optcomp.cma /home/gabori/.opam/4.02.3/lib/ppx_driver/./ppx_driver.cma /home/gabori/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv.cma /home/gabori/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv_deriving.cma /home/gabori/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv.cma -ppx ppx_cstruct --as-ppx
```
> When I add the quotes, everything works fine:
```
 -ppx "/home/gabori/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/gabori/.opam/4.02.3/lib/ppx_core/./ppx_core.cma /home/gabori/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv_expander.cma /home/gabori/.opam/4.02.3/lib/ppx_optcomp/./ppx_optcomp.cma /home/gabori/.opam/4.02.3/lib/ppx_driver/./ppx_driver.cma /home/gabori/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv.cma /home/gabori/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv_deriving.cma /home/gabori/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv.cma" -ppx "ppx_cstruct --as-ppx"
```

For reference, the incriminated `jbuild` file looks like the following:
```
(* -*- tuareg -*- *)
#require "unix"

let flags pkgs =
  let cmd = "ocamlfind ocamlc -verbose" ^ (
    List.fold_left (fun acc pkg -> acc ^ " -package " ^ pkg) "" pkgs
  ) in
  let ic = Unix.open_process_in
    (cmd ^ " | grep -oEe '-ppx (\"([^\"\\]|\\.)+\"|\w+)'")
  in
  let rec go ic acc =
    try go ic (acc ^ " " ^ input_line ic) with End_of_file -> close_in ic; acc
  in
  go ic ""

let () = Printf.ksprintf Jbuild_plugin.V1.send {|
(library
 ((name nbd)
  (public_name nbd)
  (flags (:standard -w -34-32 %s))
  (libraries
   (cstruct
    io-page
    lwt
    mirage-types.lwt
    ppx_sexp_conv
    sexplib))
  )
 )
|} (flags ["ppx_sexp_conv"; "cstruct.ppx"])
```
(note that the generated flags are correctly quoted in the jbuild file)

**Comment by mseri** [comment]
I think it should be fixed by https://github.com/janestreet/jbuilder/commit/6e48e70a74616f34e54a21926d57a42b09832b26

**Comment by gaborigloi** [comment]
It seems that it's still not fixed, I've just tried with the dev version of jbuilder and it's still not quoted.

**Comment by mseri** [comment]
I have a simple fix:
```diff
diff --git a/src/merlin.ml b/src/merlin.ml
index e48dec3..fc36544 100644
--- a/src/merlin.ml
+++ b/src/merlin.ml
@@ -55,7 +55,12 @@ let dot_merlin sctx ~dir ({ requires; flags; _ } as t) =
         let flags =
           match flags with
           | [] -> []
-          | _  -> ["FLG " ^ String.concat flags ~sep:" "]
+          | _  ->
+              let escaped_flags = List.map (fun flag ->
+                if String.contains flag ' ' then
+                  Printf.sprintf "\"%s\"" flag
+                else flag) flags in
+              ["FLG " ^ String.concat escaped_flags ~sep:" "]
         in
         let dot_merlin =
           List.concat
```
It's not the most elegant thing but does the job. @diml I am happy to make a PR if you think it could be affecting some other use-case.

**Comment by diml** [comment]
@mseri, PR is welcome, this looks like a bug indeed. Note that there is a `quote_for_shell` function in import.ml to quote if needed. 

I assume that https://github.com/whitequark/ppx_deriving/pull/141 will make the hack no longer necessary.

**Comment by mseri** [comment]
Thanks. I'll use that and make a PR!

The `ppx_deriving` PR will solve the issue for us in the future (hopefully near), once we are able to update our baggage of upstream libraries. But until then we will need to use the workaround :-(
